### PR TITLE
Hover links (highlighting)

### PR DESCRIPTION
**Pull request by derekbrokeit**
Links/anchors change highlighting if the cursor is on them. 
I have also added a description of this feature to README.

I wanted this feature, so I went ahead and made it :)
If you have any questions please ask. 

--Edit

Sorry for adding so many additional commits. I realized that there were 2 bugs in the first commit.

### CODE REVIEW

**Comment by yuratomo** [comment]
It's a nice idea. I pulled the request. Thanks!!

**Comment by derekbrokeit** [comment]
Thanks for accepting! I just want to add one additional point. The algorithm used here is linear O(n) with tags_list to keep it simple and easy to understand. 

**Problem**: more links + scrolling far down a page --> might slow down vim if the page is big enough. 

This can be fixed if another list (or tags_list updated) existed with all tags arranged per line i.e. 

```
      tags_list_lines[ n ] := [ list of all tags on line n ]
```

It's just a thought, but I didn't want to modify the code too much. It might have become a monster!

**Comment by yuratomo** [comment]
I have confirmed the phenomenon.
I would like to be able to specify the delay time to HoverHilight.
And I define the delay time to 100ms by default.

**Comment by derekbrokeit** [comment]
When I get some free time in the next few days, I will see if I can speed up the algorithm. It may require modifying the loop that creates tags_list. Is that ok with you?

**Comment by yuratomo** [comment]
I'm all right.
I hope that the following pages will be displayed quickly.

http://unkar.org/r/unix/1202050038

**Comment by derekbrokeit** [comment]
Thank you for the link to a good example. I will use pages like this for testing.

Until I can fix the speed, I suggest turning off the hover-highlighting on a page like that.

**Comment by yuratomo** [comment]
At present, hover-link-highlight turn off at default.
Because performance downed.
Excepting the parsing process, "matchadd" at every cursor movement seems to have lowered performance.
I think if it is difficult to improve performance, i want to be able to On / Off function dynamically.

**Comment by derekbrokeit** [comment]
Yes, that is a good idea for now, until performance is improved.

**Pull request merged**
