### PR TITLE
Hover speed-boost

### PR DESCRIPTION
**Pull request by derekbrokeit**
Improvements to the speed of the link "hover" highlighting.

A new variable `b:link_index_list` was created for this task. 

```
" example:
" on line 55, extract link/anchor #2
link = b:tag_list[b:link_index_list[55][2]]
```

This may also be used to speed up link searches.

**Note**: `matchadd( ... )` is slow. Therefore, `matchadd` is only called if necessary. If the cursor is still within the previous highlighted zone, nothing is changed.

### CODE REVIEW

**Comment by derekbrokeit** [comment]
Also, this feature is still off by default.

**Comment by derekbrokeit** [comment]
Actually, I have an improvement to make that should reduce variable checks.

Please do not pull this request until I add this.

**Comment by derekbrokeit** [comment]
Change b:link_index_list into b:anchor_list                                                                                                                                                                                               

```
b:anchor_list is capable of much more and is therefore much more powerful.                                                                                                                                                                
It is a list of line-associated lists like b:link_index_list, but instead of                                                                                                                                                              
tag-indexes ( --> b:tag_list), they are complete anchors.                                                                                                                                                                                 

Right now, each anchor is a dictionary with "attr", "startCol", "endCol", and "line".                                                                                                                                                     

    " example usage                                                                                                                                                                                                                       
    " the first anchor on line 55                                                                                                                                                                                                         
    let link = b:anchor_index[55][0]                                                                                                                                                                                                      
    " the first column of the link                                                                                                                                                                                                        
    let s = link.startCol                                                                                                                                                                                                                 
    " the final column                                                                                                                                                                                                                    
    let e = link.endCol                                                                                                                                                                                                                   
    " the line                                                                                                                                                                                                                            
    let l = link.line                                                                                                                                                                                                                     
    " the link-reference                                                                                                                                                                                                                  
    let r = link.attr.href  
```

**Advantage**: If used, link searches and reference checks should be faster.

**Comment by yuratomo** [comment]
Thanks. I have confirmed that performance is up.
I merged this pull request.
And, I append the variable g:w3m#hover_delay_time.
It is a delay time until highlighting.
If you set 0, it is no delay.

**Pull request merged**
